name: Test URL

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      URL: ${{ secrets.URL }}

    steps:
      - name: Mostrar variável
        run: echo "$URL"

      - name: Fazer request
        run: curl -L "$URL"

      - name: Ver status HTTP
        run: curl -I "$URL"
