name: Test URL

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      URL: ${{ secrets.URL }}

    steps:
      - name: Mostrar URL
        run: echo "$URL"

      - name: Fazer request
        run: curl "$URL"
